<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>predictive task</name>
  <uuid>5aee59e8-9a3b-41b3-9211-07398c487398</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the machine learning scorecard computed from 
	Industry being Industry , 
	Client Info being Client ; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
