<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>set client input</name>
  <uuid>18f0eaf0-0e5d-4a29-bb20-18c4e30b1600</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new ML model input where
		the clientannualrevenue is the Annual Revenue of 'Client Info',
		the clientemployeenumber is the Number of Employees of 'Client Info',
		the clientexistenceduration is the Company Age of 'Client Info' ,
		the clientindustry is 0 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
